### ISSUE TITLE
In the profile view, mid-size images are cropped, rather than just scaled

### ISSUE THREAD

**Issue by typofixer** [WreckedAvent/slimCat#360]
This is a bug report. The bug occurs in in 4.11 and 5.00 dev (and presumably all other recent releases as well).

Clicking on a profile image thumbnail in slimCat's in-client profile viewer will bring up a medium-sized version of that image. Recently, these medium-sized views of the profile images have been getting rescaled *and cropped*, rather than just rescaled, which I'm fairly certain isn't intended behavior.

![Image provided for illustration of the issue.](http://i.imgur.com/qjpbzdT.png)

**Comment by WreckedAvent** [comment]
@Tyroie know anything about this? I think you were the last to poke around with the image displaying code.

**Comment by Tyroie** [comment]
Oh! Off the top of my head, I remember having to grab the width & size of the image in order to center it on the screen. My best guess is that it's failing to grab that info, for some reason.
I'm guessing F-list changed some stuff about how it displays images? I'll take a look at the code a bit.

**Comment by Tyroie** [comment]
It seems like the profile-images.json API isn't returning `width` or `height` at all anymore. It's taken those two things out, and has added `sort_order` after everything else - and that always sets to "null" from what I've seen.

If I'm understanding things right, the `ApiProfileImage` class needs to be updated to fit that. However I'm not at all sure how to grab the needed `width` from the image now. I could try to make it display the image without using `width` at all, but I remember that being kinda crummy and messy.

**Comment by WreckedAvent** [comment]
`sort_order` should be respected now that that's a thing. The dimension removals were intentional - if you load the image into memory as bitmap you can get the dimensions if you need them, assuming the converter is in a place to load a bitmap (and is not just handling uris). If it isn't, you might just need to try w/o the metadata entirely. 

I *believe* we can get WPF to do the heavy lifting with the scaling if we just set the max width, as I assume it would try to keep the aspect ratio.

**Comment by Tyroie** [comment]
Amusingly, as far as I can manage, slimCat is already showing the images in the same order that F-list does, no matter how I change the order around! I've tried about ten times, just to make sure.

Would it be a good idea to write code to guarantee that it always respects `sort_order` anyway?

**Comment by WreckedAvent** [comment]
Nothing fancy, you'd just add it to the model (and remove `height`/`width` while you're at it) and then do a `SortBy()``.ToList()` combo in the `ProfileService`
