### ISSUE TITLE
Double spaces after user name in channel backlog in 5.00

### ISSUE THREAD

**Issue by typofixer** [WreckedAvent/slimCat#363]
This is a bug report (I *think* - I suppose it's possible that it was an intentional change). The bug applies to slimCat 5.00 dev.

The space after a user's name in chat is doubled when compared to previous slimCat versions. This looks typographically unpleasant (jarring, even).

![Illustration of the issue](http://i.imgur.com/rfrOsuB.png)

**Comment by WreckedAvent** [comment]
Not an intentional change, just a weird consequence of auto-formatting some things.
