### ISSUE TITLE
Give gender-neutral profiles their own color

### ISSUE THREAD

**Issue by typofixer** [WreckedAvent/slimCat#369]
This is a feature request.

Currently, the names of profiles with no gender set, or the *None* gender option set, are displayed with the theme's *HighlightColor*. I want there to be an independent color for these profiles.

**Comment by WreckedAvent** [comment]
Why? There's already a crapload of genders, and only a tiny number of users who select none.

**Comment by typofixer** [comment]
That last part is simply false - there are more gender-neutral profiles online on F-Chat than cuntboy profiles, for example, yet those get their own color.

The problem with gender-neutral profile names defaulting to *HighlightColor* is that *HighlightColor* might be similar to one of the other gender colors, making color-based discernment of these different genders difficult or even impossible.

**Comment by WreckedAvent** [comment]
Did some more thinking. There's basically no risk here, as this will all be controlled by the theme. Even if this gets added, it'll have zero impact on most users as their theme will not support it, so it will only matter to the portion of users willing to mod their `colors.xaml` to change something. And really, if you want to do that, there's no reason you can't go through the hassle of juggling all of the gender colors.
