### ISSUE TITLE
Crash on recieving infinity or NaN value from server

### ISSUE THREAD

**Issue by syldrathecat** [WreckedAvent/slimCat#383]
On receiving a dice roll command with the result -inf or -nan, slimCat crashes. This may either be an exception due to the non-standard sequence of characters appearing in the JSON message, or when attempting to convert the result to an integer.

The dice roll command used to generate these results has been hot-patched on the server, but should be fixed just in case the fix isn't perfect or there's other circumstances where infinity/NaN may possibly be sent from the server that should be checked.

Example messages that caused a crash:

    RLL {"channel":"ADH-1f6e65beb53b55ab647d","endresult":-inf,"type":"dice","message":"[user]Syldra Kitty[/user] rolls -inf: [b]-inf[/b]","rolls":["-inf"],"character":"Syldra Kitty","results":[-inf]}
    RLL {"channel":"ADH-1f6e65beb53b55ab647d","endresult":-nan,"type":"dice","message":"[user]Syldra Kitty[/user] rolls nan: [b]nan[/b]","rolls":["nan"],"character":"Syldra Kitty","results":[-nan]}
    RLL {"message":"[user]Syldra Kitty[/user] rolls -inf: [b]-inf[/b]","recipient":"Syldra","endresult":-inf,"type":"dice","rolls":["-inf"],"character":"Syldra Kitty","results":[-inf]}

**Comment by WreckedAvent** [comment]
Not sure if this is a bug or a change in the server, but I hadn't heard of this one before. How does a user end up rolling this result?

**Comment by syldrathecat** [comment]
It was triggered by a long-standing bug in the server that was quickly hot-patched after it was discovered that it caused slimCat to crash. It could be triggered by variations on the roll command substituting numbers with "inf", "nan" or "1e9999" on clients that didn't validate the outgoing roll command (Desktop Client and slimCat).

It is no longer an active DoS threat, as the server validates the output of the roll command now.

**Comment by WreckedAvent** [comment]
Doing some more research, this is due to invalid JSON. slimCat doesn't attempt to parse the roll message in any special, it just parses the bbcode like any other message. But `infinity` and `NaN` are not legal JSON characters, and a client could not be reasonably expected to handle invalid things in the data transfer format.
