### ISSUE TITLE
Kinks missing from slimCat's list of search terms

### ISSUE THREAD

**Issue by typofixer** [WreckedAvent/slimCat#384]
The 'Sexism', 'Raceplay', 'Bimbofication', 'Cuddling', 'Storytelling (Narrator)' and 'Storytelling (Player)' kinks are missing from slimCat's list of search terms. F-List added these to the site a few months ago.

**Comment by WreckedAvent** [comment]
slimCat gets the terms from the site's API, and doesn't have an internal list of any kind. What's likely happening is your slimCat still has a cache of this. Since kinks almost never update, it's cached quite hard.

**Comment by typofixer** [comment]
How do I update the cache?

**Comment by WreckedAvent** [comment]
Delete `!search.xml` in `logs/character name/global`
