### ISSUE TITLE
Rolls in logs are not being read correctly

### ISSUE THREAD

**Issue by 41149512** [WreckedAvent/slimCat#386]
5.002 dev parses colons in logs as the part where the character name gets separated from the message, then puts the character name in between [user] tags, like this:

![image](https://cloud.githubusercontent.com/assets/8314479/9197406/3051ef6a-4034-11e5-9093-211fbf4a21d0.png)

This is part of the log slimCat loaded into the channel tab for me. Posts made with /me do not have clickable names, normal messages do, since the former does not have a colon in it. The problem is how rolls are saved in the log. A roll currently looks like this:

`[21:17:35] [user]Xaine[/user] spins the bottle: [user]Sebastian White[/user]`

Since the colon here is positioned after "spins the bottle", the parsed result looks like this, with [user] tags around everything that comes before it:

![image](https://cloud.githubusercontent.com/assets/8314479/9197484/d98184ba-4034-11e5-8119-c7fd561ea329.png)

Which obviously isn't how it's supposed to be. I suggest fixing this as part of #382, since simply logging a roll with something along the lines of `System:` in front of it would stop this from happening.

**Comment by WreckedAvent** [comment]
This was fixed by drastically simplifying the logging logic. Ads, rolls, normal messages and "non command commands" like /me and /warn are all treated the same way, with the exception being that ads start with [Ad].
