### ISSUE TITLE
Add token character between user name and action content to make chat log machine-interpretable

### ISSUE THREAD

**Issue by typofixer** [WreckedAvent/slimCat#387]
I wanted to create a chat statistics page for one of the rooms I frequent ([you might be familiar with the concept from IRC channels](http://www.philosophy-irc.org/channelstats/jan28-feb03-2001.html)). However, the way slimCat currently keeps logs makes it impossible to separate the user name from the content of a `/me` command using a regular expression, as there is no character token separating the two and it is therefore impossible to tell where a user name ends and the message content starts.

If I remember correctly, IRC clients like mIRC add `*` between user name and `/me` command content in their logs to solve this issue. I understand that human readability of the slimCat-generated log files is an issue, and therefore I suggest using an 'invisible' Unicode character as a separation token instead, such as the [non-breaking space character](http://www.fileformat.info/info/unicode/char/00a0/index.htm).

**Comment by WreckedAvent** [comment]
This actually causes other issues in slimCat as well, such as /me messages failing to parse 100% of the time and usually resulting in ugly logs when they are parsed "actively" in the client in modern 5.xx builds.

I am still not entirely sure what approach I want to take to solve this, but it will most likely result in a change to how logs are written in a way that users will want to read them through slimCat more, meaning it is more desirable to have a better integrated longer-term log manager and viewer.

**Comment by WreckedAvent** [comment]
This was fixed by drastically simplifying the logging logic. Ads, rolls, normal messages and "non command commands" like /me and /warn are all treated the same way, with the exception being that ads start with [Ad]. This makes them fairly easy to machine parse, as [slimCat does now](https://github.com/WreckedAvent/slimCat/blob/d0c73c4dc11a4b61d2daa293548521fb2e54c396/slimCat/Models/MessageModel.cs#L61).
