### ISSUE TITLE
Slimcat not reconizing an owner for a private room

### ISSUE THREAD

**Issue by Nahuni** [WreckedAvent/slimCat#389]
A friend of mine owns a set of rooms on f-list and he can't do room owner things on the room because slimcat returns an error to him saying that only the room's owner can do opping and such.

I don't know much about the problem, but I can tell you what I do know
1. The room(s) were made before he moved to slimcat
2. They have been open for a long time.

That is about all I can tell you, and I don't know when I will be able to get more information, mostly because he is on rather sporadically. If I can get more information, I will reply to this if and when I get it.

**Comment by WreckedAvent** [comment]
slimCat does not do any validation on commands. Those errors are coming straight from the server.

Most likely, his/her name is not capitalized correctly in the modlist.

**Comment by Nahuni** [comment]
Is there a way to get around this, or view the modlist itself? I have not started many rooms or anything, so I don't know how they all work.

Date: Sat, 5 Sep 2015 07:50:39 -0700

**Comment by WreckedAvent** [comment]
No, this is just how the server works. You cannot get around it. You can view the moderator list normally in slimCat.
