### ISSUE TITLE
Crash: System.Net.WebException was unhandled

### ISSUE THREAD

**Issue by typofixer** [WreckedAvent/slimCat#394]
Crash occurred with slimCat 5.004 on Windows 7 after restoring the OS from sleep.

![](http://i.imgur.com/q8Rq3Vp.png)
![](http://i.imgur.com/PiDK4gs.png)
![](http://i.imgur.com/VUQt6F0.png)

**Comment by WreckedAvent** [comment]
Looks like you didn't have internet, or f-list was down.
