### ISSUE TITLE
Toggle for italic styling of /me posts

### ISSUE THREAD

**Issue by AccountForPyfa** [WreckedAvent/slimCat#412]
Feature request: add a simple toggle that enables/disables the default italic text formatting of /me posts

This is something that has been bugging me for a while. I personally find italic text to be harder on the eyes than plain text, and reading through paragraphs of it is frankly awful.

**Comment by WreckedAvent** [comment]
This is certainly possible, but raises a problem in that users expect an f-chat client to do this.

**Comment by AccountForPyfa** [comment]
I made my own personal fork with the desired lack of italics, so this is a non-issue.
