### ISSUE TITLE
Moving the "..." typing indicator off of the icon?

### ISSUE THREAD

**Issue by gotmilk0112** [WreckedAvent/slimCat#420]
As it is right now, when someone is typing, it shows the little "..." animation on their profile icon. Problem is, it's often very hard to see, because it's on top of a multicolored profile image.

Would it be possible to move this element to say...beneath the name, on the tab?

Like this: http://i.imgur.com/jfS2qAx.gif

The "~" icon for indicating that they have text entered, could be placed here as well.

**Comment by WreckedAvent** [comment]
dup #403
