### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by Rinnosuke93** [WreckedAvent/slimCat#425]
Good afternoon, I am making this post because I have just redownloaded slimCat on my new hard disk and I've noticed something not working.
I'm currently using Puma 4.11 (and it's not even telling me to get the Slow Cheetah version like it used to before my old hard disk died last week) and when I go to the search tab... It's totally empty.
![1494680995050](https://cloud.githubusercontent.com/assets/17508121/26025743/78377a4e-37ee-11e7-85f4-93e6ad1438e9.jpg)
As you can see from the picture, I even tried to type stuff in and see if it'd let me do anything, but it'll constantly tell me that I need to narrow down the search 'cos it's getting too many results.

Checking around, I noticed another issue on here where it was suggested to delete the "search.xml" and did that, but it didn't solve the issue, sadly. What should I do to fix this?

Thanks in advance.

**Comment by WreckedAvent** [comment]
4.11 is no longer being maintained, so when the searching system was changed, it broke. If you want search, use 5.xx.
