### ISSUE TITLE
How to turn off font-smoothing?

### ISSUE THREAD

**Issue by Carl-Robert** [WreckedAvent/slimCat#428]
Hey!
I am running the 5.013 version of Slimcat on a Windows 10 machine. Turning off font-smoothing and ClearType from Window's settings will not fix having blurry fonts inside the software. It actually makes the issue even worse.

Is there any forced smoothing going on, hardware-acceleration or other stuff enforcing the blurrying? It is really irritating especially for a software which sole purpose is to read text.

The issue is easy to check, just turn off ClearType and the font-smoothing from the Visual Enhancements on Performance settings.

**Comment by WreckedAvent** [comment]
as far as I know, this is simply how WPF (the client's rendering engine) handles the display of text. slimCat takes no additional steps to smooth or alias text.

**Comment by Carl-Robert** [comment]
That's too bad then, as sounds like there is no way around this issue. The text is awfully blurry, so changing software.
