### ISSUE TITLE
Slimcat 5.014 signs into account but character never connects

### ISSUE THREAD

**Issue by ccoffield93** [WreckedAvent/slimCat#445]
Might have something to do with the changed chat URL. I'm able to sign in and connect on the android app, and in the F-chat web interface, but my character never connects to chat in slimCat.

**Comment by CravenAnchorite** [comment]
I'm seeing the same.

**Comment by Sluimerstand** [comment]
@ccoffield93 @CravenAnchorite I've been having the same issue, but venturing into the slimCat channel (by logging in via the webchat) I asked and was provided a potential solution. It does require you to have Microsoft Framework 4.8 installed and it does not work on Windows 7, sadly.

I advise you to do the same as I don't want to step on any toes by providing the files and instructions here, just in case.

**Comment by Axaia** [comment]
Hi, I have a version working on Windows 7 and 10 over here: [https://github.com/Axaia/slimCat/releases](https://github.com/Axaia/slimCat/releases)

**Comment by WreckedAvent** [comment]
fixed with #446
